/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_SeigeTowerNorthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_SeigeTowerNorthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_SeigeTowerNorthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 5716 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 5716 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 5721 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 5721 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1201 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 2, 5 );
			ac = new AddonComponent( 1203 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 1204 );
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 1197 );
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 1197 );
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 1197 );
			AddComponent( ac, -1, 2, 5 );
			ac = new AddonComponent( 1202 );
			AddComponent( ac, -1, 3, 5 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 1, 3, 5 );
			ac = new AddonComponent( 1195 );
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 1196 );
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 1195 );
			AddComponent( ac, 1, 2, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 2, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 1, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 3, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, -1, -2, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 1, -2, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 2, -2, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, -1, 25 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, -1, 25 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 0, 25 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 1, 25 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, -1, -2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 1, -2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 2, -2, 25 );
			ac = new AddonComponent( 1204 );
			AddComponent( ac, -1, -1, 25 );
			ac = new AddonComponent( 1197 );
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 1197 );
			AddComponent( ac, -1, 1, 25 );
			ac = new AddonComponent( 1202 );
			AddComponent( ac, -1, 2, 25 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 1, -1, 25 );
			ac = new AddonComponent( 1203 );
			AddComponent( ac, 2, -1, 25 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 0, 25 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 1, 25 );
			ac = new AddonComponent( 1201 );
			AddComponent( ac, 2, 2, 25 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 1, 2, 25 );
			ac = new AddonComponent( 2171 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 2212 );
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 2210 );
			AddComponent( ac, 1, 0, 17 );
			ac = new AddonComponent( 2212 );
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 2210 );
			AddComponent( ac, -1, -1, 37 );
			ac = new AddonComponent( 1202 );
			AddComponent( ac, -1, 1, 45 );
			ac = new AddonComponent( 1201 );
			AddComponent( ac, 2, 1, 45 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 1, 1, 45 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 0, 45 );
			ac = new AddonComponent( 1203 );
			AddComponent( ac, 2, -1, 45 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 1, -1, 45 );
			ac = new AddonComponent( 1196 );
			AddComponent( ac, 1, 0, 45 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 1196 );
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 1196 );
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 1196 );
			AddComponent( ac, 0, 2, 5 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 0, -2, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 0, -2, 25 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 0, -1, 25 );
			ac = new AddonComponent( 1196 );
			AddComponent( ac, 0, 0, 25 );
			ac = new AddonComponent( 1195 );
			AddComponent( ac, 0, 1, 25 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 0, 2, 25 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 0, -1, 45 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 0, 1, 45 );
			ac = new AddonComponent( 1195 );
			AddComponent( ac, 0, 0, 45 );
			ac = new AddonComponent( 2212 );
			AddComponent( ac, 1, 0, 45 );
			ac = new AddonComponent( 2210 );
			AddComponent( ac, 1, -1, 57 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 0, 25 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 1, 25 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 2, 2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 1, 2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 0, 2, 25 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, -1, 2, 25 );
			ac = new AddonComponent( 8562 );
			AddComponent( ac, 1, 3, 21 );
			ac = new AddonComponent( 1487 );
			AddComponent( ac, 2, 3, 21 );
			ac = new AddonComponent( 8563 );
			AddComponent( ac, 0, 3, 21 );
			ac = new AddonComponent( 8562 );
			AddComponent( ac, -1, 3, 21 );
			ac = new AddonComponent( 8562 );
			AddComponent( ac, 2, 2, 41 );
			ac = new AddonComponent( 8563 );
			AddComponent( ac, 1, 2, 41 );
			ac = new AddonComponent( 8562 );
			AddComponent( ac, 0, 2, 41 );
			ac = new AddonComponent( 8563 );
			AddComponent( ac, -1, 2, 41 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 2, 1, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 1, 1, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 0, 1, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, -1, 1, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, -1, 3, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 1, 45 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, 0, 45 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, 2, -1, 45 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 1, 45 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, 0, 45 );
			ac = new AddonComponent( 551 );
			AddComponent( ac, -2, -1, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, -1, -2, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 2, -2, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 1, -2, 45 );
			ac = new AddonComponent( 552 );
			AddComponent( ac, 0, -2, 45 );
			ac = new AddonComponent( 1195 );
			AddComponent( ac, 0, 0, 65 );
			ac = new AddonComponent( 1200 );
			AddComponent( ac, 0, -1, 65 );
			ac = new AddonComponent( 1204 );
			AddComponent( ac, -1, -1, 65 );
			ac = new AddonComponent( 1202 );
			AddComponent( ac, -1, 1, 65 );
			ac = new AddonComponent( 1197 );
			AddComponent( ac, -1, 0, 65 );
			ac = new AddonComponent( 1201 );
			AddComponent( ac, 2, 1, 65 );
			ac = new AddonComponent( 1203 );
			AddComponent( ac, 2, -1, 65 );
			ac = new AddonComponent( 1199 );
			AddComponent( ac, 2, 0, 65 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 1, 1, 65 );
			ac = new AddonComponent( 1198 );
			AddComponent( ac, 0, 1, 65 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, -1, -1, 65 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, -1, 0, 65 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, -1, 1, 65 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, 0, 1, 65 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, 0, 0, 65 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, -1, -1, 70 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, -1, 0, 70 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, -1, 1, 70 );
			ac = new AddonComponent( 2173 );
			AddComponent( ac, 0, -1, 65 );
			ac = new AddonComponent( 2173 );
			AddComponent( ac, 0, 0, 69 );
			ac = new AddonComponent( 1848 );
			AddComponent( ac, 0, 1, 70 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, 0, 75 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, -1, 75 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, -3, 75 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, -2, 75 );
			ac = new AddonComponent( 555 );
			AddComponent( ac, 2, 1, 65 );
			ac = new AddonComponent( 555 );
			AddComponent( ac, 2, 0, 65 );
			ac = new AddonComponent( 555 );
			AddComponent( ac, 2, -1, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, 2, -2, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, 1, -2, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, 0, -2, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, 2, 1, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, 1, 1, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, 0, 1, 65 );
			ac = new AddonComponent( 554 );
			AddComponent( ac, -1, 1, 65 );

		}

		public AG_SeigeTowerNorthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_SeigeTowerNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_SeigeTowerNorthAddon();
			}
		}

		[Constructable]
		public AG_SeigeTowerNorthAddonDeed()
		{
			Name = "AG_SeigeTowerNorth";
		}

		public AG_SeigeTowerNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}