/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class StoneWellAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new StoneWellAddonDeed();
			}
		}

		[ Constructable ]
		public StoneWellAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 39 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 37 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 37 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 8566 );
			AddComponent( ac, 1, -1, 11 );
			ac = new AddonComponent( 8566 );
			AddComponent( ac, -1, -1, 11 );
			ac = new AddonComponent( 8566 );
			AddComponent( ac, 0, -1, 11 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 36 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 38 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 38 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 38 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 37 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 10076 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 10076 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1486 );
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 1486 );
			AddComponent( ac, -1, 0, 14 );
			ac = new AddonComponent( 1486 );
			AddComponent( ac, 1, 0, 14 );
			ac = new AddonComponent( 1487 );
			AddComponent( ac, 1, 1, 11 );
			ac = new AddonComponent( 1487 );
			AddComponent( ac, 0, 1, 11 );
			ac = new AddonComponent( 1487 );
			AddComponent( ac, -1, 1, 11 );
			ac = new AddonComponent( 5370 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 4090 );
			AddComponent( ac, 1, 2, 16 );

		}
        public override void OnComponentUsed(AddonComponent ac, Mobile from)
        {
            if (!from.InRange(GetWorldLocation(), 2))
                from.SendMessage("You are too far away.");
            else
            {
                {
                    switch (Utility.Random(5))
                    {
                        default:
                        case 0:
                            {
                                from.Say("All that work getting everything.. and all I got was a well...");
                                from.PlaySound(0x4E);
                                break;
                            }
                        case 1:
                            {
                                from.Say("Sorry.. this isnt wine so stop drinking so much of it");
                                from.PlaySound(0x4E);
                                break;
                            }

                        case 2:
                            {
                                from.Say("You see a weird looking bug in your water... JUST before you swallow it.");
                                from.PlaySound(0x4E);
                                break;
                            }

                        case 3:
                            {
                                from.Say("Next time, keep your fingers out from under the hammer, OK?");
                                from.PlaySound(0x4E);
                                break;
                            }
                        case 4:
                            {
                                from.Say(" *THUNK!!* Uh oh... wells gone dry..");
                                from.PlaySound(0x4E);
                                break;
                            }
                    }
                }
            }
        }

		public StoneWellAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class StoneWellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new StoneWellAddon();
			}
		}

		[Constructable]
		public StoneWellAddonDeed()
		{
			Name = "StoneWell";
		}

		public StoneWellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}