/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class allinonebathroomAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new allinonebathroomAddonDeed();
			}
		}

		[ Constructable ]
		public allinonebathroomAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -3, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -2, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -3, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -2, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, -3, 2 );
			ac = new AddonComponent( 1983 );
			ac.Hue = 1378;
			AddComponent( ac, -4, -3, 4 );
			ac = new AddonComponent( 1988 );
			ac.Hue = 1378;
			AddComponent( ac, -1, -3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -3, -3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -2, -3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 0, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 1, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 2, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 3, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 4, -3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 4, -3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 3, -3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 2, -3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 2, -3, 6 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 3, -3, 6 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 4, -3, 6 );
			ac = new AddonComponent( 4104 );
			AddComponent( ac, 3, -3, 8 );
			ac = new AddonComponent( 4104 );
			AddComponent( ac, 0, -3, 4 );
			ac = new AddonComponent( 6420 );
			AddComponent( ac, -1, -3, 6 );
			ac = new AddonComponent( 6420 );
			AddComponent( ac, -1, -3, 8 );
			ac = new AddonComponent( 2707 );
			AddComponent( ac, 2, -3, 8 );
			ac = new AddonComponent( 4242 );
			ac.Hue = 1378;
			AddComponent( ac, 0, -3, 9 );
			ac = new AddonComponent( 4172 );
			ac.Hue = 1378;
			AddComponent( ac, 0, -3, 6 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 4, -3, 8 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, -2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, -1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 0, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 4, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -3, -2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -3, -1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -3, 0, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -3, 1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -3, 2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -3, 3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -3, 4, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -2, -2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -2, -1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -2, 0, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -2, 1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -2, 2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1266;
			AddComponent( ac, -2, 3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -2, 4, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, -2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, -1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 0, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 1, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 2, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 3, 2 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 4, 2 );
			ac = new AddonComponent( 1985 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 4, 4 );
			ac = new AddonComponent( 1986 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 4, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -3, 4, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -2, 4, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -1, -2, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -1, -1, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 0, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 1, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 2, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -1, 3, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -4, -2, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -4, -1, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 0, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 1, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 2, 4 );
			ac = new AddonComponent( 1982 );
			ac.Hue = 1378;
			AddComponent( ac, -4, 3, 4 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1378;
			AddComponent( ac, 0, 2, 2 );
			ac = new AddonComponent( 4100 );
			ac.Hue = 1259;
			AddComponent( ac, -3, 1, 9 );
			ac = new AddonComponent( 4100 );
			ac.Hue = 1264;
			AddComponent( ac, -3, 0, 9 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1378;
			AddComponent( ac, -2, -2, 5 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1378;
			AddComponent( ac, -3, -2, 5 );
			ac = new AddonComponent( 2842 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -4, -2, 6 );
			ac = new AddonComponent( 2842 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -4, 3, 6 );
			ac = new AddonComponent( 6813 );
			AddComponent( ac, -4, 1, 6 );
			ac = new AddonComponent( 5914 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 3, 10 );
			ac = new AddonComponent( 10296 );
			AddComponent( ac, 0, 3, 8 );
			ac = new AddonComponent( 3126 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 3126 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -3, 3, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -3, 0, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -3, 1, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -3, 2, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -2, -2, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -2, 1, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -2, 3, 5 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 2613;
			AddComponent( ac, -3, -2, 5 );

		}

		public allinonebathroomAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class allinonebathroomAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new allinonebathroomAddon();
			}
		}

		[Constructable]
		public allinonebathroomAddonDeed()
		{
			Name = "allinonebathroom";
		}

		public allinonebathroomAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}