
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class stepFancyRoundEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1813, 0, -1, 0}, {1804, -1, -1, 0}, {1819, 0, 1, 0}// 1	2	3	
			, {1802, -1, 2, 0}, {1811, 1, 1, 0}, {1813, 1, 0, 0}// 4	5	6	
			, {1811, 0, 2, 0}, {1801, -1, 1, 0}, {1801, -1, 0, 0}// 7	8	9	
			, {1820, 0, 0, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new stepFancyRoundEAddonDeed();
			}
		}

		[ Constructable ]
		public stepFancyRoundEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public stepFancyRoundEAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class stepFancyRoundEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new stepFancyRoundEAddon();
			}
		}

		[Constructable]
		public stepFancyRoundEAddonDeed()
		{
			Name = "stepFancyRoundE";
		}

		public stepFancyRoundEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}