
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CastleJoinAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1930, 4, -1, 0}, {1930, 4, 0, 0}, {1930, 4, 1, 0}// 1	2	3	
			, {1930, 4, 2, 0}, {1928, -3, -1, 0}, {1928, -3, 0, 0}// 4	5	6	
			, {1928, -3, 1, 0}, {1928, -3, 2, 0}, {1928, 3, -1, 0}// 7	8	9	
			, {1928, 3, 0, 0}, {1928, 3, 1, 0}, {1928, 3, 2, 0}// 10	11	12	
			, {1932, -4, -1, 0}, {1932, -4, 0, 0}, {1932, -4, 1, 0}// 13	14	15	
			, {1932, -4, 2, 0}, {1932, -3, -1, 5}, {1932, -3, 0, 5}// 16	17	18	
			, {1932, -3, 1, 5}, {1932, -3, 2, 5}, {1930, 3, -1, 5}// 19	20	21	
			, {1930, 3, 0, 5}, {1930, 3, 1, 5}, {1930, 3, 2, 5}// 22	23	24	
			, {1928, -2, -1, 5}, {1928, -2, 0, 5}, {1928, -2, 1, 5}// 25	26	27	
			, {1928, -2, 2, 5}, {1928, -1, -1, 5}, {1928, -1, 0, 5}// 28	29	30	
			, {1928, -1, 1, 5}, {1928, -1, 2, 5}, {1928, 0, -1, 5}// 31	32	33	
			, {1928, 0, 0, 5}, {1928, 0, 1, 5}, {1928, 0, 2, 5}// 34	35	36	
			, {1928, 1, -1, 5}, {1928, 1, 0, 5}, {1928, 1, 1, 5}// 37	38	39	
			, {1928, 1, 2, 5}, {1928, 2, -1, 5}, {1928, 2, 0, 5}// 40	41	42	
			, {1928, 2, 1, 5}, {1928, 2, 2, 5}, {762, -2, 2, 5}// 43	44	45	
			, {762, -1, 2, 5}, {762, 0, 2, 5}, {762, 1, 2, 5}// 46	47	48	
			, {762, 2, 2, 5}, {762, 3, 2, 5}, {762, -3, 2, 5}// 49	50	51	
			, {762, -3, -2, 5}, {762, -2, -2, 5}, {762, -1, -2, 5}// 52	53	54	
			, {762, 0, -2, 5}, {762, 1, -2, 5}, {762, 2, -2, 5}// 55	56	57	
			, {762, 3, -2, 5}, {762, 4, 2, 2}, {762, -4, 2, 2}// 58	59	60	
			, {762, -4, -2, 0}, {762, 4, -2, 0}// 61	62	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CastleJoinAddonDeed();
			}
		}

		[ Constructable ]
		public CastleJoinAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2852, -4, -2, 10, 0, 29, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 2852, -4, 2, 12, 0, 29, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 2852, 4, 2, 12, 0, 29, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 2852, 4, -2, 10, 0, 29, "", 1);// 66

		}

		public CastleJoinAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CastleJoinAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CastleJoinAddon();
			}
		}

		[Constructable]
		public CastleJoinAddonDeed()
		{
			Name = "CastleJoin";
		}

		public CastleJoinAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}