
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OrnateFountainAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1812, -4, 1, 0}, {1810, -4, -1, 0}, {1814, -3, -1, 0}// 1	2	3	
			, {1810, -3, -2, 0}, {1814, -2, -2, 0}, {1810, -2, -3, 0}// 4	5	6	
			, {1814, -1, -3, 0}, {1810, -1, -4, 0}, {1813, 1, -4, 0}// 7	8	9	
			, {1816, 1, -3, 0}, {1813, 2, -3, 0}, {1816, 2, -2, 0}// 10	11	12	
			, {1811, 2, 3, 0}, {1811, 1, 4, 0}, {1819, 2, 2, 0}// 13	14	15	
			, {1819, 1, 3, 0}, {1821, -2, 2, 0}, {1821, -3, 1, 0}// 16	17	18	
			, {1812, -1, 4, 0}, {1821, -1, 3, 0}, {1812, -2, 3, 0}// 19	20	21	
			, {1812, -3, 2, 0}, {1802, 0, 4, 0}, {1804, 0, -4, 0}// 22	23	24	
			, {1805, -4, 0, 0}, {279, -2, -1, 0}, {279, -1, -2, 0}// 25	26	27	
			, {280, 0, -3, 0}, {280, 0, 2, 0}, {280, -1, 1, 0}// 28	29	30	
			, {280, -2, 0, 0}, {280, 1, 1, 0}, {280, 2, 0, 0}// 31	32	33	
			, {280, 2, -1, 0}, {280, 1, -2, 0}, {281, -1, 2, 0}// 34	35	36	
			, {281, -2, 1, 0}, {281, -3, 0, 0}, {281, 0, 2, 0}// 37	38	39	
			, {281, 1, 1, 0}, {281, 2, 0, 0}, {281, 1, -1, 0}// 40	41	42	
			, {281, 0, -2, 0}, {282, 0, 1, 0}, {282, 1, 0, 0}// 43	44	45	
			, {1175, -3, 0, 4}, {1175, -2, -1, 4}, {1175, -2, 1, 4}// 46	47	48	
			, {1175, 2, -1, 4}, {1175, 2, 1, 4}, {1175, -1, -2, 4}// 49	50	51	
			, {1175, -1, 2, 4}, {1175, 1, -2, 4}, {1175, 1, 2, 4}// 52	53	54	
			, {1175, 0, -3, 4}, {1175, 0, 3, 4}, {4554, 0, 3, 4}// 55	56	57	
			, {4554, 1, 2, 4}, {4554, 2, 1, 4}, {4554, 2, -1, 4}// 58	59	60	
			, {4554, 1, -2, 4}, {4554, 0, -3, 4}, {4554, -1, -2, 4}// 61	62	63	
			, {4554, -2, -1, 4}, {4554, -3, 0, 4}, {4554, -2, 1, 4}// 64	65	66	
			, {4554, -1, 2, 4}, {6039, -2, 0, 3}, {6039, 0, 0, 3}// 67	68	69	
			, {6039, 2, 0, 3}, {6039, 0, -2, 3}, {6039, 0, 0, 3}// 70	71	72	
			, {6039, 0, 2, 3}, {13456, -1, 1, 3}, {13456, -1, 0, 3}// 73	74	75	
			, {13456, -1, -1, 3}, {13456, 0, -1, 3}, {13456, 1, -1, 3}// 76	77	78	
			, {13456, 1, 0, 3}, {13456, 1, 1, 3}, {13456, 0, 1, 3}// 79	80	81	
			, {13591, 0, 0, 3}, {13561, 0, 0, 3}, {13456, 0, 0, 13}// 82	83	84	
			, {5021, 0, 0, 13}, {1813, 3, -2, 0}, {1816, 3, -1, 0}// 85	86	87	
			, {1813, 4, -1, 0}, {1811, 4, 1, 0}, {1819, 3, 1, 0}// 88	89	90	
			, {1811, 3, 2, 0}, {1803, 4, 0, 0}, {1175, 3, 0, 4}// 91	92	93	
			, {4554, 3, 0, 4}// 94	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OrnateFountainAddonDeed();
			}
		}

		[ Constructable ]
		public OrnateFountainAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public OrnateFountainAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OrnateFountainAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OrnateFountainAddon();
			}
		}

		[Constructable]
		public OrnateFountainAddonDeed()
		{
			Name = "OrnateFountain";
		}

		public OrnateFountainAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}