
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SerenityWallSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {271, 0, 1, 0}, {270, 1, 1, 0}, {271, 1, 0, 0}// 1	2	3	
			, {271, 0, 0, 0}, {6042, 0, 1, 4}, {6042, 1, 1, 4}// 4	5	6	
			, {13488, 0, 1, 4}, {13488, 1, 1, 4}, {13585, 0, 0, 4}// 7	8	9	
			, {13585, 1, 0, 4}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SerenityWallSouthAddonDeed();
			}
		}

		[ Constructable ]
		public SerenityWallSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SerenityWallSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SerenityWallSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SerenityWallSouthAddon();
			}
		}

		[Constructable]
		public SerenityWallSouthAddonDeed()
		{
			Name = "SerenityWallSouth";
		}

		public SerenityWallSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}