
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class bonfireAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {12793, -2, -2, 0}, {12793, -1, -2, 0}, {12793, 0, -2, 0}// 1	2	3	
			, {12793, 1, -2, 0}, {12793, 2, -2, 0}, {6024, 2, -2, 0}// 4	5	6	
			, {4963, 1, -2, 0}, {4965, 2, -2, 0}, {3387, 0, 0, 0}// 7	8	9	
			, {3387, 0, 0, 0}, {3387, 1, -1, 0}, {3387, 1, -1, 0}// 10	11	12	
			, {3387, 0, 1, 0}, {3387, 1, 0, 0}, {3387, 1, 0, 0}// 13	14	15	
			, {3387, 2, 0, 0}, {3388, 1, 0, 0}, {3388, 0, 1, 0}// 16	17	18	
			, {3388, 0, 0, 0}, {3388, 1, -1, 0}, {12793, -2, -1, 0}// 19	20	41	
			, {12793, -2, 0, 0}, {12793, -2, 1, 0}, {12793, -1, -1, 0}// 42	43	44	
			, {12793, -1, 0, 0}, {12793, -1, 1, 0}, {12793, 0, -1, 0}// 45	46	47	
			, {12793, 0, 0, 0}, {12793, 0, 1, 0}, {12793, 1, -1, 0}// 48	49	50	
			, {12793, 1, 0, 0}, {12793, 1, 1, 0}, {12793, 2, -1, 0}// 51	52	53	
			, {12793, 2, 0, 0}, {12793, 2, 1, 0}, {12789, -2, 2, 0}// 54	55	56	
			, {12789, -1, 2, 0}, {12789, 0, 2, 0}, {12789, 1, 2, 0}// 57	58	59	
			, {12789, 2, 2, 0}, {12794, 1, 2, 0}, {12794, -1, 2, 0}// 60	61	62	
			, {6025, 2, 2, 0}, {6022, -2, 2, 0}, {4963, -2, 0, 0}// 63	64	65	
			, {4963, -2, 2, 0}, {4963, 1, 2, 2}, {4963, 0, -1, 12}// 66	67	68	
			, {4963, 2, -1, 0}, {4963, 2, 2, 0}, {4963, 0, 2, 0}// 69	70	71	
			, {4965, -2, 1, 0}, {4965, -1, 2, 0}, {4965, 2, 2, 3}// 72	73	74	
			, {4965, 2, 0, 0}, {4965, 2, 1, 0}, {4965, 2, 0, 0}// 75	76	77	
			, {4965, 2, 0, 0}, {4967, 2, 1, 0}, {4967, -2, 1, 0}// 78	79	80	
			, {4967, 1, 2, 0}, {4967, -1, 2, 0}, {4967, 0, 2, 3}// 81	82	83	
			, {4970, 0, 2, 0}, {6021, 3, -1, 0}, {6021, 3, 0, 0}// 84	85	86	
			, {6021, 3, 1, 0}, {6020, -2, 3, 0}, {6020, -1, 3, 0}// 87	88	89	
			, {6020, 0, 3, 0}, {6020, 1, 3, 0}, {6020, 2, 3, 0}// 90	91	92	
			, {6006, 3, 1, 0}, {6006, -1, 3, 0}, {6006, 3, -1, 0}// 93	94	95	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new bonfireAddonDeed();
			}
		}

		[ Constructable ]
		public bonfireAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 14732, 1, 0, 0, 0, 1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 14732, 0, -1, 0, 0, 1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 14732, 1, -1, 0, 0, 1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 14732, -1, 1, 0, 0, 1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 14732, 2, 0, 12, 0, 1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 14732, 0, 0, 0, 0, 1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 14732, 1, 1, 0, 0, 1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 14732, 1, 0, 0, 0, 1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 14742, -1, -1, 0, 0, 1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 14742, 0, 0, 0, 0, 1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 14742, 0, 0, 0, 0, 1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 14742, 1, 0, 12, 0, 1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 14742, 1, 0, 12, 0, 1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 14742, 1, 0, 12, 0, 1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 14742, 0, -1, 0, 0, 1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 14742, 1, 0, 0, 0, 1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 14742, 2, 0, 0, 0, 1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 14742, 2, -1, 0, 0, 1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 14732, 0, 1, 0, 0, 1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 14732, 1, -1, 0, 0, 1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 3555, -1, 1, 0, 0, 1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 3555, 1, 1, 4, 0, 1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 3555, 1, 0, 0, 0, 1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 3555, 0, 1, 3, 0, 1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 3555, 0, 1, 0, 0, 1, "", 1);// 100

		}

		public bonfireAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class bonfireAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new bonfireAddon();
			}
		}

		[Constructable]
		public bonfireAddonDeed()
		{
			Name = "bonfire";
		}

		public bonfireAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}