
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CarpetBlueGold7x7Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2769, -2, -2, 0}, {2769, -2, -1, 0}, {2769, -2, 0, 0}// 1	2	3	
			, {2769, -2, 1, 0}, {2769, -1, -2, 0}, {2769, -1, -1, 0}// 4	5	6	
			, {2769, -1, 0, 0}, {2769, -1, 1, 0}, {2769, 0, -2, 0}// 7	8	9	
			, {2769, 0, -1, 0}, {2769, 0, 0, 0}, {2769, 0, 1, 0}// 10	11	12	
			, {2769, 1, -2, 0}, {2769, 1, -1, 0}, {2769, 1, 0, 0}// 13	14	15	
			, {2769, 1, 1, 0}, {2769, 2, -2, 0}, {2769, 2, -1, 0}// 16	17	18	
			, {2769, 2, 0, 0}, {2769, 2, 1, 0}, {2771, -3, -3, 0}// 19	20	21	
			, {2773, 3, -3, 0}, {2774, -3, -2, 0}, {2774, -3, -1, 0}// 22	23	24	
			, {2774, -3, 0, 0}, {2774, -3, 1, 0}, {2775, -2, -3, 0}// 25	26	27	
			, {2775, -1, -3, 0}, {2775, 0, -3, 0}, {2775, 1, -3, 0}// 28	29	30	
			, {2775, 2, -3, 0}, {2776, 3, -2, 0}, {2776, 3, -1, 0}// 31	32	33	
			, {2776, 3, 0, 0}, {2776, 3, 1, 0}, {2769, -2, 2, 0}// 34	35	36	
			, {2769, -1, 2, 0}, {2769, 0, 2, 0}, {2769, 1, 2, 0}// 37	38	39	
			, {2769, 2, 2, 0}, {2770, 3, 3, 0}, {2772, -3, 3, 0}// 40	41	42	
			, {2774, -3, 2, 0}, {2776, 3, 2, 0}, {2777, -2, 3, 0}// 43	44	45	
			, {2777, -1, 3, 0}, {2777, 0, 3, 0}, {2777, 1, 3, 0}// 46	47	48	
			, {2777, 2, 3, 0}// 49	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CarpetBlueGold7x7AddonDeed();
			}
		}

		[ Constructable ]
		public CarpetBlueGold7x7Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CarpetBlueGold7x7Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CarpetBlueGold7x7AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CarpetBlueGold7x7Addon();
			}
		}

		[Constructable]
		public CarpetBlueGold7x7AddonDeed()
		{
			Name = "CarpetBlueGold7x7";
		}

		public CarpetBlueGold7x7AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}