
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CarpetCinnamon5x5Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2795, -1, -1, 0}, {2795, -1, 0, 0}, {2795, -1, 1, 0}// 1	2	3	
			, {2795, 0, -1, 0}, {2795, 0, 0, 0}, {2795, 0, 1, 0}// 4	5	6	
			, {2795, 1, -1, 0}, {2795, 1, 0, 0}, {2795, 1, 1, 0}// 7	8	9	
			, {2787, 2, 2, 0}, {2788, -2, -2, 0}, {2789, -2, 2, 0}// 10	11	12	
			, {2790, 2, -2, 0}, {2791, -2, -1, 0}, {2791, -2, 0, 0}// 13	14	15	
			, {2791, -2, 1, 0}, {2792, -1, -2, 0}, {2792, 0, -2, 0}// 16	17	18	
			, {2792, 1, -2, 0}, {2793, 2, -1, 0}, {2793, 2, 0, 0}// 19	20	21	
			, {2793, 2, 1, 0}, {2794, -1, 2, 0}, {2794, 0, 2, 0}// 22	23	24	
			, {2794, 1, 2, 0}// 25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CarpetCinnamon5x5AddonDeed();
			}
		}

		[ Constructable ]
		public CarpetCinnamon5x5Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CarpetCinnamon5x5Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CarpetCinnamon5x5AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CarpetCinnamon5x5Addon();
			}
		}

		[Constructable]
		public CarpetCinnamon5x5AddonDeed()
		{
			Name = "CarpetCinnamon5x5";
		}

		public CarpetCinnamon5x5AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}