
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ConversationPitGreenEAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ConversationPitGreenEAddonDeed();
			}
		}

		[ Constructable ]
		public ConversationPitGreenEAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1848, 0, -3, 0, 762, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2796, 0, -1, 0, 763, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1859, 3, -3, 0, 762, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2796, -1, -1, 0, 762, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1848, -1, -2, 0, 762, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1848, -1, -3, 0, 762, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2796, 0, -2, 0, 762, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1848, 2, -3, 0, 762, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1848, 1, -3, 0, 762, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1848, -2, -2, 0, 762, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4632, 2, -2, 0, 762, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2796, 1, -2, 0, 762, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 4632, 1, -2, 0, 762, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2796, -1, -2, 0, 762, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 4633, -1, -1, 0, 762, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2796, 3, -2, 0, 762, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 4632, 0, -2, 0, 762, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1848, -2, -1, 0, 762, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1857, -2, -3, 0, 762, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1848, 3, -2, 0, 762, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2796, 2, -2, 0, 762, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2796, 2, -1, 0, 763, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2796, 1, -1, 0, 763, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2776, 3, -1, 0, 763, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1848, 2, 3, 0, 762, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 4633, -1, 1, 0, 762, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2796, -1, 2, 0, 762, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1848, 1, 3, 0, 762, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2796, -1, 0, 0, 762, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1848, -2, 0, 0, 762, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2796, 3, 2, 0, 762, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2796, 2, 1, 0, 763, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2796, 0, 1, 0, 763, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1858, 3, 3, 0, 762, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2796, -1, 1, 0, 762, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1848, -1, 3, 0, 762, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1848, -1, 2, 0, 762, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2796, 0, 0, 0, 763, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1848, -2, 1, 0, 762, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 4633, -1, 0, 0, 762, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1860, -2, 3, 0, 762, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2796, 2, 0, 0, 763, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2796, 1, 0, 0, 763, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2796, 1, 1, 0, 763, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2805, 2, 2, 0, 763, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2805, 1, 2, 0, 763, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2805, 0, 2, 0, 763, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1848, 0, 3, 0, 762, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 4634, 0, 2, 0, 762, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 4634, 1, 2, 0, 762, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 4634, 2, 2, 0, 762, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1848, 3, 2, 0, 762, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1848, -2, 2, 0, 762, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 2776, 3, 0, 0, 763, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2776, 3, 1, 0, 763, -1, "", 1);// 55

		}

		public ConversationPitGreenEAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ConversationPitGreenEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ConversationPitGreenEAddon();
			}
		}

		[Constructable]
		public ConversationPitGreenEAddonDeed()
		{
			Name = "ConversationPitGreenE";
		}

		public ConversationPitGreenEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}