
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class conversationPitSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1848, -2, -2, 0}, {1848, -3, -2, 0}, {1848, -2, -1, 1}// 1	2	3	
			, {1848, -2, 3, 0}, {2758, -2, -1, 0}, {2758, -2, 0, 0}// 4	5	6	
			, {2758, -2, 1, 0}, {2758, -2, 2, 0}, {2758, -2, 3, 0}// 7	8	9	
			, {1848, -3, -1, 0}, {1848, -3, 0, 0}, {1848, -3, 1, 0}// 11	12	13	
			, {1848, -3, 2, 0}, {1848, -3, 3, 0}, {1848, 2, -2, 0}// 14	15	20	
			, {1848, 1, -2, 0}, {1848, 0, -2, 0}, {1848, -1, -2, 0}// 21	22	23	
			, {1848, 3, -2, 0}, {1848, 2, 3, 0}, {1848, 3, -1, 0}// 25	26	27	
			, {1848, 3, 0, 0}, {1848, 3, 1, 0}, {2758, -1, -1, 0}// 28	29	30	
			, {2758, -1, 0, 0}, {2758, -1, 1, 0}, {2758, -1, 2, 0}// 31	32	33	
			, {2758, -1, 3, 0}, {2758, 0, -1, 0}, {2758, 0, 0, 0}// 34	35	36	
			, {2758, 0, 1, 0}, {2758, 0, 2, 0}, {2758, 0, 3, 0}// 37	38	39	
			, {2758, 1, -1, 0}, {2758, 1, 0, 0}, {2758, 1, 1, 0}// 40	41	42	
			, {2758, 1, 2, 0}, {2758, 1, 3, 0}, {1848, 2, -1, 0}// 43	44	58	
			, {2758, 2, 0, 0}, {2758, 2, 1, 0}, {2758, 2, 2, 0}// 62	63	64	
			, {1848, 3, 2, 0}, {1848, 3, 3, 0}// 68	69	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new conversationPitSAddonDeed();
			}
		}

		[ Constructable ]
		public conversationPitSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5036, -3, 1, 5, 33, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4633, -2, 0, 0, 1031, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 4633, -2, 1, 0, 1031, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 4633, -2, 2, 0, 1031, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 11676, -2, -1, 13, 1150, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 5032, 0, -2, 5, 33, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2723, -1, 0, 0, 0, -1, "table", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2724, 1, 0, 0, 0, -1, "table", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2725, -1, 2, 0, 0, -1, "table", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2840, 1, 2, 0, 0, -1, "table", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2720, 0, 2, 0, 0, -1, "table", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2719, 1, 1, 0, 0, -1, "table", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2721, -1, 1, 0, 0, -1, "table", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2722, 0, 0, 0, 0, -1, "table", 1);// 52
			AddComplexComponent( (BaseAddon) this, 7386, 1, 2, 8, 1150, -1, "frosted glass", 1);// 53
			AddComplexComponent( (BaseAddon) this, 7386, 0, 2, 8, 1150, -1, "frosted glass", 1);// 54
			AddComplexComponent( (BaseAddon) this, 7386, 0, 1, 8, 1150, -1, "frosted glass", 1);// 55
			AddComplexComponent( (BaseAddon) this, 7386, 1, 1, 8, 1150, -1, "frosted glass", 1);// 56
			AddComplexComponent( (BaseAddon) this, 5035, 3, 1, 5, 33, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 4632, -1, -1, 0, 1031, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 4632, 0, -1, 0, 1031, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 4632, 1, -1, 0, 1031, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 4635, 2, 0, 0, 1031, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 4635, 2, 1, 0, 1031, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 4635, 2, 2, 0, 1031, -1, "", 1);// 67

		}

		public conversationPitSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class conversationPitSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new conversationPitSAddon();
			}
		}

		[Constructable]
		public conversationPitSAddonDeed()
		{
			Name = "conversationPitS";
		}

		public conversationPitSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}