
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DWSantasFireplaceSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1302, -1, -1, 0}, {1302, -1, 0, 0}, {26, -1, -1, 0}// 1	2	3	
			, {28, -1, -2, 0}, {29, -2, -2, 0}, {27, -2, -1, 0}// 4	5	6	
			, {2328, -1, -1, 18}, {11225, -1, 0, 9}, {11227, -2, 0, 3}// 7	8	9	
			, {2788, -1, 1, 0}, {2789, -1, 3, 0}, {2791, -1, 2, 0}// 10	11	12	
			, {2867, -1, 2, 0}, {7138, -1, 0, 0}, {3272, -1, 3, 4}// 13	14	16	
			, {3874, -1, 3, 6}, {3876, -1, 3, 9}, {3881, -1, 3, 8}// 18	19	20	
			, {3887, -1, 3, 6}, {3873, -1, 3, 7}, {3860, -1, 3, 5}// 21	22	23	
			, {3877, -1, 3, 5}, {1302, 0, -1, 0}, {1302, 0, 0, 0}// 24	25	26	
			, {1302, 1, -1, 0}, {1302, 1, 0, 0}, {28, 0, -2, 0}// 27	28	29	
			, {28, 1, -2, 0}, {28, 2, -2, 0}, {1302, 2, -1, 0}// 30	31	32	
			, {1302, 2, 0, 0}, {26, 2, -1, 0}, {27, 1, -1, 0}// 33	34	35	
			, {37, 0, -1, 12}, {37, 1, -1, 12}, {2328, 2, -1, 18}// 36	37	38	
			, {11225, 2, 0, 9}, {11227, 2, 0, 3}, {1993, 0, -1, 10}// 40	41	42	
			, {9004, 0, 0, 4}, {1993, 1, -1, 10}, {2790, 2, 1, 0}// 43	45	46	
			, {2787, 2, 3, 0}, {2792, 0, 1, 0}, {2792, 1, 1, 0}// 47	48	49	
			, {2793, 2, 2, 0}, {2794, 0, 3, 0}, {2794, 1, 3, 0}// 50	51	52	
			, {2795, 0, 2, 0}, {2795, 1, 2, 0}, {2879, 1, 2, 0}// 53	54	55	
			, {8073, 1, 2, 6}, {2519, 1, 2, 6}, {11233, 1, 2, 7}// 56	57	58	
			, {7137, 0, -1, 0}, {7134, 0, -1, 0}, {9008, 2, 0, 1}// 59	60	61	
			, {11234, 1, 2, 7}, {1993, 0, -1, 11}, {1993, 1, -1, 11}// 62	63	64	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DWSantasFireplaceSouthAddonDeed();
			}
		}

		[ Constructable ]
		public DWSantasFireplaceSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4551, -1, 3, 0, 1436, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 10299, -1, 3, 16, 1360, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3555, 0, -1, 3, 0, 1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 4012, 0, -1, 1, 0, 1, "", 1);// 44

		}

		public DWSantasFireplaceSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DWSantasFireplaceSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DWSantasFireplaceSouthAddon();
			}
		}

		[Constructable]
		public DWSantasFireplaceSouthAddonDeed()
		{
			Name = "DWSantasFireplaceSouth";
		}

		public DWSantasFireplaceSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}