
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DWSledgeWReindeersAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {14933, 2, 1, 9}, {14951, -2, 4, 9}, {323, 2, -4, 9}// 3	4	5	
			, {14941, 1, 2, 9}, {324, 2, -5, 11}, {14951, 0, 3, 9}// 8	9	10	
			, {322, 1, -1, 9}, {323, 0, -1, 9}, {14944, -2, 5, 9}// 11	14	15	
			, {14951, -1, 4, 9}, {14933, 1, 1, 9}, {323, 2, 0, 9}// 16	17	21	
			, {324, 0, -1, 11}, {323, 0, 0, 9}, {323, 2, -1, 9}// 24	25	26	
			, {323, 0, -4, 9}, {324, 0, 0, 11}, {323, 0, -3, 9}// 29	30	35	
			, {324, 2, -2, 12}, {323, 2, -3, 9}, {324, 2, -4, 11}// 36	37	39	
			, {324, 2, -5, 13}, {11225, 2, 0, 16}, {324, 2, -3, 11}// 40	42	43	
			, {324, 2, -4, 13}, {324, 2, -1, 11}, {324, 2, -3, 12}// 47	49	50	
			, {323, 2, -2, 9}, {324, 2, 0, 11}, {11225, 1, 0, 16}// 52	54	60	
			, {14935, 0, 2, 9}, {324, 2, -5, 9}, {322, 2, -1, 9}// 62	63	65	
			, {14951, -1, 3, 9}, {323, 0, -2, 9}, {324, 2, -2, 11}// 66	73	74	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DWSledgeWReindeersAddonDeed();
			}
		}

		[ Constructable ]
		public DWSledgeWReindeersAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1194, 1, -4, 14, 133, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 18, 1, -5, 14, 133, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 25, 0, -2, 14, 133, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 9003, 2, -3, 23, 1283, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 9003, 1, -4, 25, 1108, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 21, 2, -3, 14, 133, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 9003, 2, -3, 25, 2955, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 21, 0, -3, 14, 133, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 9002, 1, -4, 19, 424, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 9003, 2, -4, 27, 1650, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1194, 1, -2, 14, 133, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 9003, 2, -3, 19, 91, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1194, 2, -4, 14, 133, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1194, 1, -3, 14, 133, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1194, 1, -1, 14, 133, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 18, 1, -1, 13, 133, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 9003, 2, -3, 19, 1287, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 18, 2, -5, 14, 133, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 9003, 1, -3, 16, 1194, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1194, 2, -1, 14, 133, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 25, 2, -2, 14, 133, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 9003, 2, -3, 21, 2428, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 25, 2, -1, 13, 133, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2861, 1, -2, 14, 367, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 9003, 2, -4, 21, 463, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 9002, 2, -3, 16, 21, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 9003, 1, -3, 18, 1284, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 18, 2, -1, 13, 133, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 25, 0, -1, 13, 133, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1194, 2, -3, 14, 133, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 9003, 1, -3, 20, 1284, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 21, 0, -4, 14, 133, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 9003, 2, -4, 24, 22, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 2861, 2, -2, 14, 367, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 21, 2, -4, 14, 133, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 9003, 1, -4, 14, 587, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1194, 2, -2, 14, 133, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 9003, 1, -3, 14, 2955, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 4050, 3, -5, 1, 1360, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 4050, 3, -4, 1, 1360, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 4050, 3, -2, 0, 1360, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 4050, 3, -3, 0, 1360, -1, "", 1);// 78

		}

		public DWSledgeWReindeersAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DWSledgeWReindeersAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DWSledgeWReindeersAddon();
			}
		}

		[Constructable]
		public DWSledgeWReindeersAddonDeed()
		{
			Name = "DWSledgeWReindeers";
		}

		public DWSledgeWReindeersAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}