
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DWSantasFireplaceEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1302, -1, -1, 0}, {1302, 0, -1, 0}, {27, -2, -1, 0}// 1	2	3	
			, {29, -2, -2, 0}, {28, -1, -2, 0}, {26, -1, -1, 0}// 4	5	6	
			, {2327, -1, -1, 18}, {11226, 0, -1, 5}, {11228, 0, -2, 4}// 7	8	9	
			, {2788, 1, -1, 0}, {2790, 3, -1, 0}, {2792, 2, -1, 0}// 10	11	12	
			, {2866, 2, -1, 0}, {7135, 0, -1, 0}, {3272, 3, -1, 4}// 13	14	16	
			, {3874, 3, -1, 6}, {3876, 3, -1, 9}, {3881, 3, -1, 8}// 18	19	20	
			, {3887, 3, -1, 6}, {3873, 3, -1, 7}, {3860, 3, -1, 5}// 21	22	23	
			, {3877, 3, -1, 5}, {1302, -1, 0, 0}, {1302, -1, 1, 0}// 24	25	26	
			, {1302, -1, 2, 0}, {1302, 0, 0, 0}, {1302, 0, 1, 0}// 27	28	29	
			, {1302, 0, 2, 0}, {27, -2, 0, 0}, {27, -2, 1, 0}// 30	31	32	
			, {27, -2, 2, 0}, {28, -1, 1, 0}, {26, -1, 2, 0}// 33	34	35	
			, {2327, -1, 2, 18}, {38, -1, 0, 12}, {38, -1, 1, 12}// 36	37	38	
			, {11226, 0, 2, 6}, {11228, 0, 2, 9}, {1997, -1, 0, 10}// 41	42	43	
			, {1997, -1, 1, 10}, {9005, 0, 0, 4}, {2789, 1, 2, 0}// 44	45	46	
			, {2787, 3, 2, 0}, {2791, 1, 0, 0}, {2791, 1, 1, 0}// 47	48	49	
			, {2793, 3, 0, 0}, {2793, 3, 1, 0}, {2794, 2, 2, 0}// 50	51	52	
			, {2795, 2, 0, 0}, {2795, 2, 1, 0}, {2880, 2, 1, 0}// 53	54	55	
			, {8075, 2, 1, 6}, {2519, 2, 1, 6}, {11234, 2, 1, 7}// 56	57	58	
			, {7134, -1, 0, 0}, {7137, -1, 0, 0}, {9008, 0, 2, 1}// 59	60	61	
			, {11233, 2, 1, 7}, {1997, -1, 0, 11}, {1997, -1, 1, 11}// 62	63	64	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DWSantasFireplaceEastAddonDeed();
			}
		}

		[ Constructable ]
		public DWSantasFireplaceEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4551, 3, -1, 0, 1436, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 10299, 3, -1, 16, 1360, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 4012, -1, 0, 1, 0, 1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 3555, -1, 0, 3, 0, 1, "", 1);// 40

		}

		public DWSantasFireplaceEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DWSantasFireplaceEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DWSantasFireplaceEastAddon();
			}
		}

		[Constructable]
		public DWSantasFireplaceEastAddonDeed()
		{
			Name = "DWSantasFireplaceEast";
		}

		public DWSantasFireplaceEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}