
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DWXmasHeart10X10Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6078, 2, 1, 0}, {6078, -3, 0, 0}, {11162, 2, -1, 0}// 2	3	4	
			, {6078, -3, -1, 0}, {6081, 3, 4, 0}, {6078, 3, 1, 0}// 5	6	7	
			, {6078, 1, 3, 0}, {11157, -1, 1, 0}, {6078, 3, 0, 0}// 8	9	10	
			, {6078, -2, 3, 0}, {11158, 3, 1, 0}, {9006, 1, 3, 7}// 11	12	13	
			, {6078, -1, 3, 0}, {6078, 2, 4, 0}, {6089, 1, 5, 0}// 14	16	17	
			, {6078, 3, 3, 0}, {6078, 2, 3, 0}, {6078, -1, -3, 0}// 18	19	20	
			, {6078, 2, 0, 0}, {6085, -4, -2, 0}, {6092, 5, 2, 0}// 21	22	23	
			, {6078, -2, 0, 0}, {9009, -1, 2, 3}, {11160, -1, 0, 0}// 24	25	26	
			, {11160, 1, 3, 0}, {6078, 1, -2, 0}, {6078, 2, 2, 0}// 27	30	31	
			, {6087, 4, 4, 0}, {6085, -2, -4, 0}, {6078, 1, 0, 0}// 32	33	35	
			, {6088, -3, 4, 0}, {6078, 2, -2, 0}, {6084, 3, -3, 0}// 36	37	39	
			, {6078, 1, 1, 0}, {6086, 3, -4, 0}, {11174, 3, 3, 2}// 41	42	43	
			, {6084, 4, -2, 0}, {6078, -1, 1, 0}, {11159, 3, 0, 3}// 44	45	47	
			, {6078, -2, 2, 0}, {6089, 2, 5, 0}, {6078, -1, 2, 0}// 50	51	52	
			, {6078, 4, 1, 0}, {6087, 5, 3, 0}, {6078, -3, 2, 0}// 54	55	56	
			, {11234, 3, 1, 5}, {6078, 3, -1, 0}, {6085, -3, -3, 0}// 57	59	60	
			, {11158, -1, -1, 0}, {6093, 1, -1, 2}, {6078, 3, -2, 0}// 61	62	64	
			, {6089, -1, 5, 0}, {9007, -1, 0, 5}, {6090, -4, 2, 0}// 65	66	68	
			, {6078, 1, 4, 0}, {6090, -4, 1, 0}, {6078, -1, 0, 0}// 69	70	71	
			, {6083, -3, -2, 0}, {6093, -1, 2, 2}, {11161, 2, 3, 0}// 72	73	74	
			, {6090, -4, 0, 0}, {6078, 0, -3, 0}, {6078, -2, -2, 0}// 75	76	77	
			, {11173, 0, 3, 3}, {6090, -4, -1, 0}, {6078, 3, 2, 0}// 78	79	80	
			, {6078, -3, 1, 0}, {6081, 4, 3, 0}, {6093, -1, 0, 2}// 81	82	84	
			, {6078, 0, 3, 0}, {6082, -3, 3, 0}, {6078, 0, 2, 0}// 85	87	88	
			, {6078, 0, -2, 0}, {6083, -2, -3, 0}, {6078, -2, -1, 0}// 90	91	92	
			, {6078, 2, -1, 0}, {6078, -1, 4, 0}, {11173, -1, 2, 0}// 93	95	96	
			, {6093, 3, 0, 2}, {6078, 1, -1, 0}, {6094, 0, -1, 3}// 98	99	100	
			, {6078, -2, 1, 0}, {6094, 1, 3, 3}, {6078, 4, 2, 0}// 101	102	104	
			, {11157, 3, 0, 0}, {6094, 3, 3, 3}, {6092, 5, 1, 0}// 105	106	107	
			, {6086, 4, -3, 0}, {6092, 5, -1, 0}, {6093, 3, 1, 2}// 108	109	110	
			, {6078, 0, 1, 0}, {6091, -1, -4, 0}, {11162, 1, -1, 1}// 111	112	113	
			, {6078, 1, 2, 0}, {6088, -2, 5, 0}, {6091, 0, -4, 0}// 114	115	118	
			, {6091, 1, -4, 0}, {6091, 2, -4, 0}, {6089, 0, 5, 0}// 119	120	121	
			, {11174, 3, 2, 0}, {11233, 0, 3, 9}, {9007, 3, 0, 6}// 122	123	124	
			, {11160, 0, -1, 0}, {6078, 1, 2, 6}, {6078, -1, -2, 0}// 125	126	128	
			, {6088, -4, 3, 0}, {6078, 0, 0, 0}, {6082, -2, 4, 0}// 129	130	131	
			, {6078, 2, -3, 0}, {6078, 4, 0, 0}, {6078, 4, -1, 0}// 132	133	134	
			, {6078, 0, 4, 0}, {6078, -1, -1, 0}, {9009, 2, -1, 5}// 135	136	137	
			, {6086, 5, -2, 0}, {6078, 0, -1, 0}, {6078, 1, -3, 0}// 138	140	141	
			, {6087, 3, 5, 0}, {6092, 5, 0, 0}, {3206, 0, -1, 6}// 142	143	145	
			, {3206, 3, 3, 8}// 146	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DWXmasHeart10X10AddonDeed();
			}
		}

		[ Constructable ]
		public DWXmasHeart10X10Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3635, 4, 3, 1, 0, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 266, 2, 2, 2, 1153, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3555, -2, -3, 6, 0, 1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 3635, 3, -3, 0, 0, 1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3555, -3, -2, 6, 0, 1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 6417, 2, 1, 5, 38, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 5168, 3, 2, 7, 45, 1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 3635, -3, 3, 0, 0, 1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 3635, -3, -2, 0, 0, 1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 3635, -2, -3, 0, 0, 1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 5168, -1, 1, 9, 310, 1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 3635, 3, 4, 1, 0, 1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 3635, -2, 4, 0, 0, 1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 3635, 4, -2, 0, 0, 1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 3555, 3, -3, 6, 0, 1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 5168, -1, -1, 8, 90, 1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 3555, -3, 3, 6, 0, 1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 5168, 2, 3, 9, 40, 1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 3555, 3, 4, 7, 0, 1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 5168, 3, 0, 13, 0, 1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 3555, 4, -2, 6, 0, 1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 3555, 4, 3, 7, 0, 1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 6418, 1, 2, 5, 38, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 5168, 1, -1, 12, 54, 1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 3555, -2, 4, 6, 0, 1, "", 1);// 144

		}

		public DWXmasHeart10X10Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DWXmasHeart10X10AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DWXmasHeart10X10Addon();
			}
		}

		[Constructable]
		public DWXmasHeart10X10AddonDeed()
		{
			Name = "DWXmasHeart10X10";
		}

		public DWXmasHeart10X10AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}