
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DWYuleFireAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3118, -2, 1, 0}, {3119, -1, -3, 0}, {3120, -1, 1, 0}// 1	3	4	
			, {3120, 0, -3, 0}, {3119, -2, -3, 0}, {3120, -2, -2, 0}// 6	8	9	
			, {3120, -1, -3, 0}, {3119, -1, 0, 0}, {3389, -3, 0, 0}// 13	20	33	
			, {3388, 0, -3, 0}, {3562, -2, 0, 6}, {3562, 0, 1, 5}// 34	52	53	
			, {3317, -2, 3, 0}, {3318, -1, 3, 0}, {3319, 0, 3, 0}// 61	62	63	
			, {3119, 1, -2, 0}, {3118, 1, -1, 0}, {3389, 2, -2, 0}// 65	67	72	
			, {3315, 3, -1, 0}, {3316, 3, 0, 0}, {3120, 3, 1, 0}// 81	82	83	
			, {3387, 2, 3, 0}, {3388, 2, 3, 0}, {3118, 2, 2, 0}// 86	87	88	
			, {3089, 2, 3, 8}, {3097, 2, 2, 4}, {3389, 3, 2, 0}// 89	90	91	
			, {3089, 2, 2, 1}, {3097, 3, 2, 7}// 92	93	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DWYuleFireAddonDeed();
			}
		}

		[ Constructable ]
		public DWYuleFireAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3117, -2, 0, 0, 1898, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3117, 0, 1, 0, 1898, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3118, -2, -1, 0, 1898, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3090, -1, -1, 3, 1899, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3098, -1, 0, 6, 1899, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3119, 0, -2, 0, 1899, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3120, 0, -1, 0, 1899, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3119, -1, -2, 0, 1899, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3120, -1, 0, 0, 1899, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3119, -1, -1, 0, 1899, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3119, 0, 0, 0, 1899, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3119, 0, -1, 1, 1895, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3645, -1, -2, 0, 1899, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 3647, 0, -1, 2, 1899, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 3645, -1, 0, 0, 1899, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3647, -1, 0, 3, 1899, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2473, 0, -1, 0, 1899, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2473, -1, -1, 0, 1899, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2473, 0, 0, 1, 1899, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 3108, 0, -2, 1, 1899, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 3088, 0, -1, 5, 1899, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3645, -1, 1, 1, 1895, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3286, 0, -1, 12, 1899, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3388, 0, 0, 9, 1899, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 14734, 0, 0, 31, 0, 1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 14734, -1, 0, 6, 0, 1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 14742, 0, 0, 10, 0, 1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 15930, 0, -2, 3, 0, 1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 15920, 0, -1, 5, 0, 1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 15930, 0, 0, 9, 0, 1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 15920, 0, 0, 7, 0, 1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 14742, 0, -1, 17, 0, 1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 14742, 0, -1, 23, 0, 1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 14742, 0, -1, 7, 0, 1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 14742, 0, -2, 0, 0, 1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 3555, -1, 1, 10, 0, 1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 3555, 0, 1, 7, 0, 1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 7137, 0, 1, 6, 1898, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 7133, 0, -3, 0, 1898, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 7136, 0, 0, 0, 1898, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 7136, -2, -1, 0, 1898, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 3561, 0, 0, 3, 0, 1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 3561, -2, 0, 1, 0, 1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 3561, -2, 0, 6, 0, 1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 14734, 0, 1, 3, 0, 1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 3561, 0, 0, 5, 0, 1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 3555, -1, 1, 2, 0, 1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 3561, -1, 1, 1, 0, 1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3094, 1, 0, 0, 1895, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 3118, 1, 0, 0, 1895, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 3119, 1, -1, 0, 1898, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 3647, 1, -2, 0, 1895, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 3387, 1, -1, 0, 1899, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 3389, 1, -1, 5, 1895, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 14742, 1, -2, 18, 0, 1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 14734, 1, -1, 12, 0, 1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 14742, 1, -1, 3, 0, 1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 3555, 1, 0, 6, 0, 1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 3555, 2, -1, 15, 0, 1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 7134, 1, -1, 4, 1898, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 3561, 1, -1, 1, 0, 1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 3561, 1, -1, 9, 0, 1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 3561, 1, 0, 3, 0, 1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 14742, 1, -1, 24, 0, 1, "", 1);// 85

		}

		public DWYuleFireAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DWYuleFireAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DWYuleFireAddon();
			}
		}

		[Constructable]
		public DWYuleFireAddonDeed()
		{
			Name = "DWYuleFire";
		}

		public DWYuleFireAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}