// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class PicnicElven1Addon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new PicnicElven1AddonDeed();}}
		[ Constructable ]
		public PicnicElven1Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3149 );
			AddComponent( ac, 3, 2, 1 );

			ac = new AddonComponent( 3342 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 3149 );
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 2429 );
			AddComponent( ac, 2, 1, 12 );

			ac = new AddonComponent( 3319 );
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 3316 );
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 3315 );
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 3340 );
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 2503 );
			AddComponent( ac, 1, 1, 9 );

			ac = new AddonComponent( 3318 );
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 2451 );
			AddComponent( ac, 1, 0, 6 );

			ac = new AddonComponent( 5640 );
			AddComponent( ac, 1, 0, 10 );

			ac = new AddonComponent( 8750 );
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 3318 );
			AddComponent( ac, 1, -1, 0 );

			ac = new AddonComponent( 3204 );
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 3149 );
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 3316 );
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 3315 );
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 3204 );
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 3149 );
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 3317 );
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 2424 );
			AddComponent( ac, -2, 1, 15 );

			ac = new AddonComponent( 2585 );
			AddComponent( ac, -2, 1, 14 );


		}
		public PicnicElven1Addon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class PicnicElven1AddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new PicnicElven1Addon();}}
		[Constructable]
		public PicnicElven1AddonDeed(){Name = "PicnicElven1";}
		public PicnicElven1AddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}