// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class RefrigeratorSAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new RefrigeratorSAddonDeed();}}
		[ Constructable ]
		public RefrigeratorSAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1179 );
			ac.Hue = 1150;
			ac.Name = "Refrigerator";
			AddComponent( ac, 0, 0, 10 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Refrigerator";
			AddComponent( ac, 0, 0, 11 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Refrigerator";
			AddComponent( ac, 0, 0, 5 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Refrigerator";
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 7830 );
			ac.Hue = 962;
			ac.Name = "Refrigerator";
			AddComponent( ac, 1, 1, 17 );

			ac = new AddonComponent( 7830 );
			ac.Hue = 962;
			ac.Name = "Refrigerator";
			AddComponent( ac, 1, 1, 11 );


		}
		public RefrigeratorSAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class RefrigeratorSAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new RefrigeratorSAddon();}}
		[Constructable]
		public RefrigeratorSAddonDeed(){Name = "RefrigeratorS";}
		public RefrigeratorSAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}