
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class StarsGlobeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {8511, -3, -3, 0}, {8511, -1, -1, 0}, {8511, 0, 0, 0}// 1	2	3	
			, {8511, -2, 2, 0}, {8511, 1, -3, 0}, {8511, -3, 1, 0}// 4	5	6	
			, {8512, -3, -2, 0}, {8512, -3, 2, 0}, {8512, -1, 0, 0}// 7	8	9	
			, {8512, 1, 1, 0}, {8512, -1, -3, 0}, {8513, -3, -1, 0}// 10	11	12	
			, {8513, -3, 3, 0}, {8513, 0, 1, 0}, {8513, 1, -2, 0}// 13	14	15	
			, {8513, 1, 0, 0}, {8514, -3, 0, 0}, {8514, -2, 3, 0}// 16	17	18	
			, {8514, -1, 1, 0}, {8514, 0, -1, 0}, {8514, 0, 2, 0}// 19	20	21	
			, {8515, -2, -3, 0}, {8515, 1, 2, 0}, {8515, -2, 0, 0}// 22	23	24	
			, {8516, -2, -2, 0}, {8516, -2, 1, 0}, {8516, 0, 3, 0}// 25	26	27	
			, {8516, 0, -2, 0}, {8516, 1, 3, 0}, {8516, -1, 3, 0}// 28	29	30	
			, {8515, 0, -3, 0}, {8515, -1, -2, 0}, {8515, -1, 2, 0}// 31	32	33	
			, {8515, 1, -1, 0}, {8514, -2, -1, 0}, {13920, -1, -1, 0}// 34	35	37	
			, {3204, -2, 4, 5}, {9035, 1, 0, 5}, {3219, 0, 3, 0}// 40	41	43	
			, {6049, 1, 4, 0}, {6064, 0, 4, 0}, {4436, 1, 1, 0}// 44	45	46	
			, {4442, 0, 3, 2}, {4443, 0, 4, 6}, {4435, -1, 2, 0}// 47	48	49	
			, {8511, 2, -2, 0}, {8512, 2, -3, 0}, {8512, 3, 1, 0}// 50	51	52	
			, {8512, 3, -1, 1}, {8513, 3, -3, 0}, {8514, 3, -2, 0}// 53	54	55	
			, {8514, 2, 1, 0}, {8515, 2, 0, 0}, {8516, 2, -1, 0}// 56	57	58	
			, {8515, 3, 0, 0}, {3204, 4, -2, 2}, {9035, 2, 3, 27}// 59	63	64	
			, {6039, 2, 2, 0}, {6039, 2, 3, 0}, {6039, 3, 3, 0}// 67	68	69	
			, {6039, 3, 2, 0}, {6045, 3, 2, 0}, {6049, 2, 3, 0}// 70	71	72	
			, {3219, 3, 0, 0}, {3203, 4, 2, 0}, {3203, 2, 4, 0}// 73	74	75	
			, {3231, 4, 4, 0}, {3338, 3, 3, 4}, {3208, 3, 4, 0}// 76	77	78	
			, {3208, 4, 3, 0}, {6045, 4, 1, 0}, {6066, 4, 0, 0}// 79	80	81	
			, {4435, 2, 2, 3}, {4437, 2, 1, 0}, {4442, 3, 0, 6}// 82	83	84	
			, {4435, 3, 1, 21}// 85	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new StarsGlobeAddonDeed();
			}
		}

		[ Constructable ]
		public StarsGlobeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 11534, 1, 3, 1, 1150, -1, "Aphrodite", 1);// 36
			AddComplexComponent( (BaseAddon) this, 3391, -1, 3, 2, 1150, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 3224, -3, 4, 1, 1150, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 3211, 0, 4, 6, 1150, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 11535, 3, 1, 1, 1150, -1, "Venus", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3391, 3, -1, 1, 1150, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3224, 4, -3, 1, 1150, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3212, 4, 0, 5, 1150, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 3237, 2, 2, 0, 1150, -1, "", 1);// 66

		}

		public StarsGlobeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class StarsGlobeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new StarsGlobeAddon();
			}
		}

		[Constructable]
		public StarsGlobeAddonDeed()
		{
			Name = "StarsGlobe";
		}

		public StarsGlobeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}