
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class trellisSeatEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11516, 0, 0, 0}, {11516, 0, 2, 1}, {3203, 0, 0, 20}// 7	8	9	
			, {3203, 0, 1, 20}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new trellisSeatEAddonDeed();
			}
		}

		[ Constructable ]
		public trellisSeatEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2186, 0, -1, 1, 1153, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2186, 0, -1, 10, 1153, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2186, 0, 1, 1, 1153, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2186, 0, 1, 10, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1114, 0, 0, 0, 1150, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1114, 0, 1, 0, 1150, -1, "", 1);// 6

		}

		public trellisSeatEAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class trellisSeatEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new trellisSeatEAddon();
			}
		}

		[Constructable]
		public trellisSeatEAddonDeed()
		{
			Name = "trellisSeatE";
		}

		public trellisSeatEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}