/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class HeartCouchAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new HeartCouchAddonDeed();
			}
		}

		[ Constructable ]
		public HeartCouchAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1811 );
			ac.Hue = 1157;
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 1808 );
			ac.Hue = 1157;
			AddComponent( ac, 3, -2, 1 );
			ac = new AddonComponent( 1810 );
			ac.Hue = 1157;
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 1157;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 1157;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 1157;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 1157;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 1157;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 1157;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 1157;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 1157;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1157;
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1157;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1157;
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1157;
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 4586 );
			ac.Hue = 1157;
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 4587 );
			ac.Hue = 1157;
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 4587 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 4587 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 4587 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 4587 );
			ac.Hue = 1157;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 4587 );
			ac.Hue = 1157;
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 1802 );
			ac.Hue = 1157;
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 1802 );
			ac.Hue = 1157;
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 1809 );
			ac.Hue = 1157;
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 1805 );
			ac.Hue = 1157;
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 1805 );
			ac.Hue = 1157;
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 1805 );
			ac.Hue = 1157;
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 1809 );
			ac.Hue = 1157;
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1802 );
			ac.Hue = 1157;
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 1817 );
			ac.Hue = 1157;
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1157;
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1157;
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1157;
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1157;
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1157;
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1157;
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1157;
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1157;
			AddComponent( ac, 2, -2, 1 );

		}

		public HeartCouchAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HeartCouchAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HeartCouchAddon();
			}
		}

		[Constructable]
		public HeartCouchAddonDeed()
		{
			Name = "HeartCouch";
		}

		public HeartCouchAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}