/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SamspoolAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SamspoolAddonDeed();
			}
		}

		[ Constructable ]
		public SamspoolAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, -2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -4, -2, 8 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, -2, 9 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 0, -2, 9 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, -2, -2, 10 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -3, -2, 9 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 3, -2, 9 );
			ac = new AddonComponent( 3236 );
			AddComponent( ac, -4, -2, 9 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, -2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, -2, 3 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, -1, -2, 9 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, 2, -2, 9 );
			ac = new AddonComponent( 1079311134 );
			AddComponent( ac, -2, 2, 3 );
			ac = new AddonComponent( 1868 );
			AddComponent( ac, 4, -1, 3 );
			ac = new AddonComponent( 1867 );
			AddComponent( ac, 4, 2, 3 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 4, 1, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, -1, 3 );
			ac = new AddonComponent( 3542 );
			AddComponent( ac, -3, -1, 3 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 2, 2, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 2, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 2, 0, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 1, 2, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 1, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 1, 0, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 0, 2, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -1, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -1, 0, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -2, 2, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -2, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -2, 0, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -3, 2, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -3, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -3, 0, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 2, -1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 1, -1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 0, -1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -1, -1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -2, -1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -3, -1, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -4, 2, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -4, 1, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -4, 0, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -4, -1, 8 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -2, 2, 3 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 2, 8 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 0, 2, 3 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -1, 1, 3 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 3, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 3, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 3, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, 3, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 3, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 3, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -4, 3, 8 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 1, -1, 3 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -2, -1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, -1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 2, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 2, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 0, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, -1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 0, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, 2, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, 0, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, -1, 3 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, 3, 9 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 0, 3, 9 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, -1, 3, 9 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, 2, 3, 9 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, -2, 3, 9 );
			ac = new AddonComponent( 6817 );
			AddComponent( ac, 4, -1, 5 );
			ac = new AddonComponent( 6817 );
			AddComponent( ac, 4, 2, 5 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -4, -1, 9 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -4, 2, 9 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -3, 3, 9 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 3, 3, 9 );
			ac = new AddonComponent( 3236 );
			AddComponent( ac, -4, 3, 9 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, 3, -1, 9 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 3, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 3, 0, 8 );
			ac = new AddonComponent( 1865 );
			AddComponent( ac, 3, 0, 3 );
			ac = new AddonComponent( 1865 );
			AddComponent( ac, 3, 1, 3 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 4, 0, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, 2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, 1, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -4, 0, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, 2, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 3, -1, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, 3, 3 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -3, 3, 3 );
			ac = new AddonComponent( 3543 );
			AddComponent( ac, 2, -1, 3 );
			ac = new AddonComponent( 3544 );
			AddComponent( ac, -3, 2, 3 );
			ac = new AddonComponent( 3542 );
			AddComponent( ac, 2, 2, 7 );
			ac = new AddonComponent( 3543 );
			AddComponent( ac, -1, 0, 4 );
			ac = new AddonComponent( 7710 );
			AddComponent( ac, -1, 2, 4 );
			ac = new AddonComponent( 7710 );
			AddComponent( ac, -3, 0, 4 );
			ac = new AddonComponent( 7710 );
			AddComponent( ac, 1, 0, 4 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 0, 1, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, 0, 0, 8 );
			ac = new AddonComponent( 7386 );
			ac.Hue = 1264;
			AddComponent( ac, -1, 2, 8 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -3, 1, 3 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 1, 1, 3 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 2, 0, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -1, 8 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 3, 8 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 2, 2, 3 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, -4, 0, 9 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, -4, 1, 9 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, 3, 2, 9 );
			ac = new AddonComponent( 3545 );
			AddComponent( ac, 1, 1, 0 );

		}

		public SamspoolAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SamspoolAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SamspoolAddon();
			}
		}

		[Constructable]
		public SamspoolAddonDeed()
		{
			Name = "Samspool";
		}

		public SamspoolAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}