/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class samspool2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new samspool2AddonDeed();
			}
		}

		[ Constructable ]
		public samspool2Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 1822 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 1865 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, -1, -1, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, -1, 0, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, -1, 1, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 0, -1, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 0, 1, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 1, -1, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 1, 0, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 1, 1, 6 );
			ac = new AddonComponent( 7385 );
			ac.Hue = 1264;
			AddComponent( ac, 2, 0, 6 );
			ac = new AddonComponent( 7710 );
			AddComponent( ac, 0, 0, 2 );
			ac = new AddonComponent( 7710 );
			AddComponent( ac, 1, 1, 2 );
			ac = new AddonComponent( 7710 );
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 3543 );
			AddComponent( ac, -1, 1, 3 );
			ac = new AddonComponent( 3543 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 3544 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, 2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 1, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -1, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, -2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, -2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, -2, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, -1, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 0, 6 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 1, 6 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, 2, 1, 6 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, 2, -1, 6 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, -2, 2, 6 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, 2, 6 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, 2, -2, 6 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, -1, -2, 6 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -1, 2, 6 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -2, -1, 6 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, -2, 1, 6 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 0, 2, 6 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, 2, 6 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 0, -2, 6 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, -2, 6 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, -2, 0, 6 );
			ac = new AddonComponent( 1846 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 1867 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 1868 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 6817 );
			AddComponent( ac, 3, 1, 3 );
			ac = new AddonComponent( 6817 );
			AddComponent( ac, 3, -1, 3 );

		}

		public samspool2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class samspool2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new samspool2Addon();
			}
		}

		[Constructable]
		public samspool2AddonDeed()
		{
			Name = "samspool2";
		}

		public samspool2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}