/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class tappytvAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new tappytvAddonDeed();
			}
		}

		[ Constructable ]
		public tappytvAddon()
		{
			AddComponent( new AddonComponent( 7030 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 1 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 2 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 3 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 4 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 5 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 6 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 7 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 8 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 9 );
			AddComponent( new AddonComponent( 3721 ), 1, 1, 10 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 1 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 2 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 3 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 4 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 5 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 6 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 7 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 8 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 9 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 10 );
			AddComponent( new AddonComponent( 7030 ), 1, -1, 14 );
			AddComponent( new AddonComponent( 2860 ), 1, -1, 11 );
			AddComponent( new AddonComponent( 7030 ), 0, 0, 3 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 1 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 2 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 3 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 4 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 5 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 6 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 7 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 8 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 9 );
			AddComponent( new AddonComponent( 7030 ), 1, 2, 14 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 10 );
			AddComponent( new AddonComponent( 2860 ), 1, 2, 11 );
			AddComponent( new AddonComponent( 7030 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 7030 ), 1, 0, 14 );
			AddonComponent ac = null;

		}

		public tappytvAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class tappytvAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new tappytvAddon();
			}
		}

		[Constructable]
		public tappytvAddonDeed()
		{
			Name = "tappytv";
		}

		public tappytvAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}